name: "Setup"
description: "Node.js / pnpm setup"

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev libpixman-1-dev

    - name: Get pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Get Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ">=20.11.1"
        cache: "pnpm"

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Cache pnpm
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - shell: bash
      run: pnpm install
